### PR TITLE
Class name change in appindicator-gtk3-java 1.3.0

### LINKED ISSUE #19: Cryptomator doesn't start as check for native lib load is broken
On releasing `appindicator-gtk3-java` 1.3.0 I cleaned up the code and renamed the class that contains the check, whether a native library could be loaded.

This need to be reflected in `integrations-linux` as well.

### PR DESCRIPTION
**Pull request by purejava**
Fixes #19

### CODE REVIEW

**Comment by infeo** [comment]
@purejava The [build](https://github.com/cryptomator/integrations-linux/actions/runs/4970982145/jobs/9051870971?pr=20) is failing during compilation. Are you sure you made the change in 1.3.0 ?

**Comment by purejava** [comment]
Well, I was, until you asked and I re-checked. 😊

You are right. The change is [committed](https://github.com/purejava/appindicator-gtk3-java/commit/b01b5da76e941d29b413fdf5f0b6c0e200c76b78) but not yet released. I am sorry and will fix it!

**Comment by purejava** [comment]
On uploading a new version to Maven Central yesterday, I noticed that I screwed up the packaging of the artifacts as a whole.

This needs to be fixed. I'll report back, when it's done.

**Comment by infeo** [comment]
Since the CI was not triggered again, i exectuted `mvn clean verify` manually. Oll Klear.

**Pull request merged**
