### PR TITLE
Update to dbus-java 4.2.1

### PR DESCRIPTION
**Pull request by purejava**
* Needs kdewallet `1.2.7`
* Depends on https://github.com/swiesend/secret-service/pull/33

### CODE REVIEW

**Comment by swiesend** [comment]
@purejava you are fast as always! Currently I am on vaccation. I am happy to release the 2.x.x when I am back in about two weeks, as I left my laptop at home...

Danke!

**Comment by purejava** [comment]
This now has latest `kdewallet 1.2.8` and latest `secret-service 1.8.0`. The latter one is tagged, but not yet released.

**Comment by swiesend** [comment]
I have released `secret-service` as version [`1.8.0-jdk17`](https://github.com/swiesend/secret-service/tree/v1.8.0-jdk17).

**Comment by infeo** [comment]
@purejava I would like to see this PR finally through. Can you bump the secret-service dependency to `1.8.0-jdk17`?

**Comment by purejava** [comment]
> @purejava I would like to see this PR finally through. Can you bump the secret-service dependency to `1.8.0-jdk17`?

@infeo Sure. Done.

**Comment by infeo** [comment]
@purejava The build fails with 
```
Error:  /home/runner/work/integrations-linux/integrations-linux/src/main/java/org/cryptomator/linux/keychain/KDEWalletKeychainAccess.java:[12,15] cannot access org.kde.KWallet
Error:    bad class file: /home/runner/.m2/repository/org/purejava/kdewallet/1.2.8/kdewallet-1.2.8.jar(/org/kde/KWallet.class)
Error:      class file has wrong version 63.0, should be 61.0
Error:      Please remove or make sure it appears in the correct subdirectory of the classpath.
```

I see in the kdewallet pom, that the language level is set to 19:
https://github.com/purejava/kdewallet/blob/1d66d8556ec1fae8b986aacc8cdd0c1808531bf0/pom.xml#L42-L43

Is it necessary for the project? I would like to stay on a LTS version, but could also bump the dependency.

**Comment by purejava** [comment]
I am afraid I released `kdewallet` 1.2.8 with Java 19.
https://github.com/purejava/kdewallet/releases

As `secret-service` sticks with Java 17 too, I'd suggest to use `kdewallet` 1.2.7 as a dependency here instead.

**Comment by infeo** [comment]
That would be feasible.

But since dbus-java also introduced some internal performance improvements, i suggest to add the necessary `dbus-java-*` dependencies explicitly to the POM with a TODO-comment, that those can be removed once kwallet is updated.

I also noticed, that `secret-service` uses the old JNR-communication. @swiesend As i wrote in https://github.com/swiesend/secret-service/pull/36, i would love to see a release, where JNR is removed.

**Comment by purejava** [comment]
Good point @infeo.

Hopefully this fits your needs.

**Comment by swiesend** [comment]
Now there is https://github.com/swiesend/secret-service/releases/tag/v1.8.1-jdk17 with `dbus-java-transport-native-unixsocket`.

**Comment by infeo** [comment]
@purejava I think i broke the build again 😅 

I discussed with @overheadhunter if we can bump the language level. It was a solid **yes**. 
Hence, `develop` uses now jdk19. Can you merge develop and revert `https://github.com/cryptomator/integrations-linux/pull/14/commits/11e576b8c03e312bd332599c0ce677764f1eaeb7`?

**Comment by purejava** [comment]
> @purejava I think i broke the build again 😅

@infeo We'll get this nailed down, I am confident 😄 
 
> I discussed with @overheadhunter if we can bump the language level. It was a solid **yes**. Hence, `develop` uses now jdk19. Can you merge develop and revert `https://github.com/cryptomator/integrations-linux/pull/14/commits/11e576b8c03e312bd332599c0ce677764f1eaeb7`?

Sure. You mean to revert https://github.com/purejava/integrations-linux/commit/50648b34e8660a0208982b8838ad7ef1525fdb1d, not https://github.com/cryptomator/integrations-linux/pull/14/commits/11e576b8c03e312bd332599c0ce677764f1eaeb7, right?

As I am on it, I change this to `19`:
https://github.com/cryptomator/integrations-linux/blob/2c95e73c27818569cbe0da9ea7c2fb87ac6247f3/pom.xml#L97

**Comment by infeo** [comment]
Gosh darn it, you are right! Thanks again for it @purejava and thanks to @swiesend for also providing a new version.

Glad that this PR is finally through.

**Pull request merged**
